# Generated by Django 3.1.2 on 2020-11-13 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0006_portfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15')], default=5)),
                ('duration', models.CharField(choices=[('1D', '1 day'), ('1W', '1 week')], default='1D', max_length=2)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet1', to='portfolio.portfolio')),
                ('portfolio2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet2', to='portfolio.portfolio')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bet',
            },
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.CheckConstraint(check=models.Q(portfolio1__lt=django.db.models.expressions.F('portfolio2')), name='check_portfolio_ids'),
        ),
    ]
