# Generated by Django 3.1.2 on 2020-11-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_auto_20201115_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at']},
        ),
    ]
