# Generated by Django 3.1.2 on 2020-11-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_squashed_0012_auto_20201117_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={},
        ),
    ]
