# Generated by Django 3.1.2 on 2020-11-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker',
            new_name='symbol',
        ),
    ]
