# Generated by Django 3.1.2 on 2020-11-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201123_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='delta_change',
            new_name='delta',
        ),
    ]
