# Generated by Django 3.1.2 on 2020-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_ticker_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
