# Generated by Django 3.1.2 on 2020-11-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
