# Generated by Django 3.1.2 on 2020-11-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201113_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-updated_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
    ]
